Echo error message if unable to find syncthing in syncthing-start

diff --git a/localtools/files/bin/syncthing-start b/localtools/files/bin/syncthing-start
--- a/localtools/files/bin/syncthing-start
+++ b/localtools/files/bin/syncthing-start
@@ -1,5 +1,9 @@
 #!/bin/sh -e
 export PATH=/usr/pkg/bin:$PATH
+if [ ! -x /usr/pkg/bin/syncthing ] ; then
+    echo "**** Unable to locale syncthing"
+    exit 1
+fi
 if pkill syncthing ; then
     sleep 5
 fi
